### ISSUE TITLE
Keyboard shortcut does not work with external keyboard

### ISSUE THREAD

**Issue by clmcdonald** [dzhibas/SublimePrettyJson#103]
I am on a Macbook, and I have a bluetooth keyboard attached. On my Macbook's built-in keyboard, the Cmd+Ctrl+J shortcut works as expected. The exact same shortcut does not work on the external keyboard, although typing is working fine. I get no response when I try the shortcut on the external keyboard. Also, Sublime's built in shortcuts work just fine - for example I can do Cmd+Shift+P on the external keyboard and access Pretty Json that way.

**Comment by TheSecEng** [comment]
Can you check the console for errors ? Key bindings and all are handled but ST and not by the plugin.

**Comment by TheSecEng** [comment]
As no feedback has been provided, and this is likely a ST issue, closing
