### ISSUE TITLE
Sublime Packed Control can't install this plugin - error 500

### ISSUE THREAD

**Issue by Tomirad** [dzhibas/SublimePrettyJson#104]
After 7 years, this problem repeat itself from https://github.com/dzhibas/SublimePrettyJson/issues/14

I need this usefully plugin, but I can't install because the program  communicate with me printed text:

> Package Control: Error downloading package. HTTP error 500 downloading https://codeload.github.com/dzhibas/SublimePrettyJson/zip/master.
> error: Package Control
> 
> Unable to download Pretty JSON. Please view the console for more details.

Maybe this problem also too temponary. But now don't working.

**Comment by TheSecEng** [comment]
@Tomirad is this still an issue ?

**Comment by TheSecEng** [comment]
This is a connection / PC issue. Not the plugin.
