### ISSUE TITLE
validate_on_save not work

### ISSUE THREAD

**Issue by mercurykd** [dzhibas/SublimePrettyJson#106]
Windows 10 x64 1909
Sublime Text 3210

```
{
    "use_entire_file_if_no_selection": true,
    "indent": 2,
    "sort_keys": false,
    "ensure_ascii": false,
    "line_separator": ",",
    "value_separator": ": ",
    "keep_arrays_single_line": false,
    "max_arrays_line_length": 120,
    "pretty_on_save": false,
    "validate_on_save": true
}
```

No validate on save

Can I also validate when opening a file?

**Comment by pwtyler** [comment]
Also encountered on OSX 10.14.6, Sublime 3211. Validate on Save and Pretty on Save worked when I first installed a couple weeks ago, although I can't tell you with 100% confidence if I was running 3211 then, too.

**Comment by mercurykd** [comment]
![image](https://user-images.githubusercontent.com/30900414/73527089-e1c09a80-442b-11ea-98c9-a80caf09d6ba.png)

ubuntu 
v.3211

**Comment by TheSecEng** [comment]
Resolved in #111

**Comment by TheSecEng** [comment]
Will look into validation on open as being an option. 

Validate on open should be working in the ST3 branch. Will investigate.

**Comment by TheSecEng** [comment]
Identified the issue, fixes in pipeline for ST4, ST3 fix to follow
