### ISSUE TITLE
Needs a menu item

### ISSUE THREAD

**Issue by n8gray** [dzhibas/SublimePrettyJson#11]
I'm not going to remember the keybinding for this in a few days -- I need it to be in the tools menu.  Can you add a menu item or document how it's done?  Thanks!

**Comment by blackholeearth** [comment]
all commands of pretty Json in Right click Context Menu!!!!

full path:  Context.sublime-menu

create file  "Context.sublime-menu"   under  this directory  "\Sublime Text root Folder\Data\Packages\User\"  

edit "Context.sublime-menu" file with text editor  add following lines::  ( save  file . restart sublime text3)

[
	    {
	        "caption": "Pretty JSON",
	        "children":
	        [
	            {
			        "caption": "Pretty JSON: Format (Pretty Print) JSON",
			        "command": "pretty_json"
			    },
			    {
			        "caption": "Pretty JSON: Format and Sort JSON",
			        "command": "pretty_json_and_sort"
			    },
			    {
			        "caption": "Pretty JSON: Minify (compress) JSON",
			        "command": "un_pretty_json"
			    },
			    {
			        "caption": "Pretty JSON: JSON 2 XML",
			        "command": "json_to_xml"
			    },
			    {
			        "caption": "Pretty JSON: JSON query with ./jq",
			        "command": "jq_pretty_json"
			    },
			    {
			        "caption": "Pretty JSON: Validate",
			        "command": "pretty_json_validate"
			    }
	        ]
	    }
	]

**Comment by TheSecEng** [comment]
This is not currently planned, looking to keep this minimal. See above for Sublime Text support features.
