### ISSUE TITLE
Duplicate keys are incorrectly shown as valid json

### ISSUE THREAD

**Issue by rishirdua** [dzhibas/SublimePrettyJson#110]
```
{
  "a" : "x",
  "a" : "y"
}
```

The above json is incorrect as `"a"` is repeated key, but is shown as valid.
Screenshot below:

![Screen Shot 2020-04-09 at 12 18 53 PM](https://user-images.githubusercontent.com/4724852/78932464-60edd280-7a5c-11ea-906f-06625f5382b3.png)

This is shown as a valid json.

However when I do a format and sort json, it changes this to
```
{
  "a": "y"
}
```

**Comment by TheSecEng** [comment]
Resolved in #111 

<img width="217" alt="image" src="https://user-images.githubusercontent.com/32599364/79519946-5b2b5a80-8023-11ea-88d0-2ccfa3f6fff2.png">
