### ISSUE TITLE
"pretty_on_save": true jumps horizontal scroll to right when saving

### ISSUE THREAD

**Issue by wggley** [dzhibas/SublimePrettyJson#124]
Editor horizontal scroll is jumping to right, messing with the scroll, everytime we save.

**Comment by TheSecEng** [comment]
Looking into this

**Comment by wggley** [comment]
![image](https://user-images.githubusercontent.com/13734836/90541656-57d2e780-e159-11ea-9a39-631cf1aa1393.png)

**Comment by TheSecEng** [comment]
Thanks, I will work on addressing this over this week.

**Comment by TheSecEng** [comment]
> Editor horizontal scroll is jumping to right, messing with the scroll, everytime we save.

Do you have an example JSON file I can test on?

**Comment by wggley** [comment]
No sorry, I uninstalled Sublime and moved to use VS Code instead.

Thanks anyway
