### ISSUE TITLE
Do not convert Unicode encoding

### ISSUE THREAD

**Issue by smile-magic** [dzhibas/SublimePrettyJson#125]
{"admin_id":"10000","admin_name":"\u8d85\u7ea7\u7ba1\u7406\u5458","order_no":"2008110945564868"}

{
    "admin_id": "10000",
    "admin_name": "\u8d85\u7ea7\u7ba1\u7406\u5458",
    "order_no": "2008110945564868"
}

hope:
{
    "admin_id": "10000",
    "admin_name": "超级管理员",
    "order_no": "2008110945564868"
}
Sublime Text : Dev Channel,Build 4081
Pretty Json: Lasest

**Comment by TheSecEng** [comment]
You need to disable `ensure_ascii` for this behavior

**Comment by smile-magic** [comment]
> 您需要`ensure_ascii`为此行为禁用

NIce! Many thanks!
