### ISSUE TITLE
Don't override cmd+r key binding

### ISSUE THREAD

**Issue by rchl** [dzhibas/SublimePrettyJson#127]
Could the default override for `cmd+r` (and equivalent on other platforms) be removed or disabled by default? I believe there can be a setting that controls if it should be enabled or there can just be instructions to enable it manually for those who want it.

https://github.com/dzhibas/SublimePrettyJson/blob/26541438aff1756059214d87c691fb61f032e4a7/Default%20(OSX).sublime-keymap#L8-L14

The issue with it is that it doesn't even handle JSON with trailing commas (and comments too I guess) which are common in ST (for example all configuration preferences) so it breaks the default functionality, showing just an error like:
![Screenshot 2020-08-19 at 22 42 30](https://user-images.githubusercontent.com/153197/90721879-0726d000-e2ba-11ea-8857-d1236e50e7a0.png)

**Comment by FichteFoll** [comment]
A more lenient fix might be to change the selector to `source.json - source.json.sublime` instead, which I just did in an override.

**Comment by rchl** [comment]
But `source.json.sublime` is a scope that comes from PackageDev so it would only help people who have it installed. It would still be problematic for people who want to use ctrl+r/cmd+r otherwise.

And sublime JSON files are not the only ones that can have trailing commas or comments even.

**Comment by FichteFoll** [comment]
> But source.json.sublime is a scope that comes from PackageDev so it would only help people who have it installed. It would still be problematic for people who want to use ctrl+r/cmd+r otherwise.

I'm approaching this from the position that ctrl+r simply does not provide any use for standard JSON files, similar to how [YAML Nav](https://github.com/ddiachkov/sublime-yaml-nav) works. I do agree with you, however, that this key override was *very unexpected* for me, as I did not think a package for formatting JSON would *also* override my symbol navigation key binding. Not having this binding by default (gated by a setting or just not at all) or splitting it off into a separate package are definitely viable options here.

> And sublime JSON files are not the only ones that can have trailing commas or comments even.

Sure, that's a separate bug in my book that needs fixing regardless.
