### ISSUE TITLE
Not working on ST4

### ISSUE THREAD

**Issue by maegul** [dzhibas/SublimePrettyJson#128]
Getting error `Expecting value: line 1 column 1 (char 0)` when trying to prettify JSON files.
These files work fine with python's `json` module and with this package on ST3.
I installed directly from this repo today to double check and had the same problem.

Example of JSON (pulled from the web) that didn't work with me as described above:

```
{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {},
      "source": [
        "# Trainer notes",
        "\n",
        "Copyright"
      ]
    },
    {
      "cell_type": "markdown",
      "metadata": {
        "toc": true
      },
      "source": [
        "<h1>Table of Contents<span class=\"tocSkip\"></span></h1>\n",
        "<div class=\"toc\"><ul class=\"toc-item\"><li><span></span></div>"
      ]
    }
  ]
}
```

**Comment by lucaschultz** [comment]
I get the same error.

**Comment by thefunkjunky** [comment]
I'm not aware of a Sublime Text 4, but this happens to me on ST 3.2.2 build 3221.  Makes this plugin basically unusable for me.

**Comment by maegul** [comment]
*Sublime Text 4 is the new version of Sublime Text.  It is currently in beta and available only to licence holders.  It should be released pretty soon apparently.*


For the maintainers of this project @lucaschultz and @thefunkjunky (and anyone else), it might be helpful to paste in examples of JSON text that are causing problems (as well as any that are not if they exist).

**Comment by canted** [comment]
Apparently it is any JSON at all.  For example, these all produce the error

`{}`
`[]`
`{"a": 1 }`

**Comment by jingyuexing** [comment]
sublime version:4100
```
reloading settings Packages/User/Preferences.sublime-settings
Traceback (most recent call last):
  File "I:\Programming\sublime_text_4100\Lib\python38\sublime_plugin.py", line 1378, in is_visible_
    ret = self.is_visible()
  File "I:\Programming\sublime_text_4100\Data\Installed Packages\Pretty JSON.sublime-package\PrettyJson.py", line 381, in is_visible
TypeError: 'NoneType' object is not iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "I:\Programming\sublime_text_4100\Lib\python38\sublime_plugin.py", line 1380, in is_visible_
    ret = self.is_visible()
  File "I:\Programming\sublime_text_4100\Data\Installed Packages\Pretty JSON.sublime-package\PrettyJson.py", line 381, in is_visible
TypeError: 'NoneType' object is not iterable
```

**Comment by TheSecEng** [comment]
Updating to fix ST4 Support

**Comment by guitaristtom** [comment]
Has this been fixed yet? Or is it still in the pipeline?

I'm still having this issue today on `build 4107` of Sublime Text and `v1.0.3` of Pretty JSON

**Comment by TheSecEng** [comment]
Is yours installed via package control?

**Comment by guitaristtom** [comment]
> A few questions
> 
>     1. Is this installed via Package Control?
Yes it is

>     2. Is this reproducible?
Most likely? This is a fresh version of Sublime Text build 4107, with just package control and Pretty JSON in it. 

I'm not sure if it helps or not, but I am on Linux.

**Comment by TheSecEng** [comment]
Thanks, I've push a new release that hopefully resolves these issues. This should populate within Package Control soon

**Comment by guitaristtom** [comment]
Looks like it fixed it. Thank you!

**Comment by Drizzt321** [comment]
@TheSecEng I'm still getting this error. Uninstalled/reinstalled from PC, says it's v1.0.5, and I'm ST4 build 4107. Is this the right version from Package Control with the fix?

**Comment by TheSecEng** [comment]
@Drizzt321 I am now able to reproduce this. I am investigating it now

**Comment by justinnichols** [comment]
Sublime Text 4 (build 4107)
Pretty JSON v1.0.5

In case this helps at all...

Attempting to run "Pretty JSON: Format JSON" on the following JSON snippet, results in the associated error
`{ "foo": "bar" }`

Error: sequence item 2: expected str instance, NoneType found

**Comment by saurabh-cimpress** [comment]
+1

**Comment by steven-lai** [comment]
I think this resolved it for me - https://github.com/dzhibas/SublimePrettyJson/issues/116#issuecomment-631271780

**Comment by Drizzt321** [comment]
v1.1.1 seems to have solved it for me, working!
