### ISSUE TITLE
JSON串包含中文，格式化之后中文变成了Unicode

### ISSUE THREAD

**Issue by thomas-tsx** [dzhibas/SublimePrettyJson#132]
原JSON为：{"key1":"测试1","key2":"测试2","key3":"测试3"}，格式化之后变成：
{
    "key1": "\u6d4b\u8bd51",
    "key2": "\u6d4b\u8bd52",
    "key3": "\u6d4b\u8bd53"
}
想请问一下该问题如何解决，谢谢。
操作系统：MacOS

**Comment by TheSecEng** [comment]
What version of Sublime and do you have  `"ensure_ascii": true,` in your settings?

**Comment by thomas-tsx** [comment]
version:sublime text4
after add "ensure_ascii" : true, this question is still exist








&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dzhibas/SublimePrettyJson"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月4日(星期二) 晚上10:45
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [dzhibas/SublimePrettyJson] JSON串包含中文，格式化之后中文变成了Unicode (#132)





 
What version of Sublime and do you have  "ensure_ascii": true, in your settings?
 
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or unsubscribe.



今天所做的一切，都是为了我们约定的那天！

**Comment by androidCircle** [comment]
Preferences  - Package Settings - Pretty Json - Settings   
add  "ensure_ascii": false,

**Comment by TheSecEng** [comment]
@thomas-tsx as noted by @androidCircle set to `"ensure_ascii": false` and this should solve the issue. Closing for now
