### ISSUE TITLE
Strings inside of arrays get modified in some cases

### ISSUE THREAD

**Issue by tryashtar** [dzhibas/SublimePrettyJson#134]
Sorry if this is a duplicate, I couldn't find anything.
When I format this JSON, the string inside gets modified to include spaces:
```py
# array changes
["a,b,c"]
    ↓
["a, b, c"]

# object is fine though
{"a,b,c":"a,b,c"}
    ↓
{
   "a,b,c": "a,b,c"
}
```

**Comment by TheSecEng** [comment]
Is this still occurring? I am not able to reproduce this at all

https://user-images.githubusercontent.com/32599364/119579322-03593a00-bd73-11eb-84f0-3de50b1aa3ca.mp4

**Comment by tryashtar** [comment]
Oh, it looks like it only happens for me when `keep_arrays_single_line` is set to true in the settings

**Comment by TheSecEng** [comment]
Great catch, working on a fix

**Comment by TheSecEng** [comment]
Fixed in latest release. Please allow a 3 hour window for Package Control to pull new release

**Comment by tryashtar** [comment]
Thank you so much! You rock 😄

**Comment by tryashtar** [comment]
Oh by the way, quick question... I just updated, and now it really likes formatting lists like this:
```json
[1,
   2,
   3]
```
Did something weird change? Is there a new setting I missed?

**Comment by TheSecEng** [comment]
Will look into this

**Comment by tryashtar** [comment]
That's the entire snippet; if I write
```json
[1,2,3]
```
and format it, that's the result I get.

It probably has something to do with Sublime 4 and might be my fault... here are my settings though:
```json
{
    "max_arrays_line_length": 100,
    "indent": 3,
    "keep_arrays_single_line": true,
    "brace_newline": false,
    "bracket_newline": false
}
```

**Comment by tolyanja** [comment]
Hello! i have same problem!
maybe problem was in os.linesep. i tried to change `content.split(os.linesep)` to `content.split('\n') `and it works.

**Comment by tryashtar** [comment]
@tolyanja That fixed it for me too, until I realized that it breaks objects in lists.
```json
[{"a":"b"}]
    ↓
[{, "a": "b", }]
```

**Comment by TheSecEng** [comment]
Is the video here what you would expect ?

https://github.com/dzhibas/SublimePrettyJson/issues/138

**Comment by tryashtar** [comment]
That looks fine to me, although with a line that long I'd probably want it to do multiline, I think there's a setting for that

**Comment by TheSecEng** [comment]
Fixed with latest release
