### ISSUE TITLE
[Sublime 4017] [Error]: sequence item 2: expected str instance, NoneType found 

### ISSUE THREAD

**Issue by t3link** [dzhibas/SublimePrettyJson#135]
OS Version: Windows 10 20H2
Sublime Text Version: Stable Build 4107

<img width="454" alt="format_mnify" src="https://user-images.githubusercontent.com/78793804/119118405-bb79a080-ba5c-11eb-91a0-95bcefef78df.png">

`

**Comment by zliuva** [comment]
I had the same issue and weirdly what worked was to:

* remove pretty JSON
* install it again
* RESTART Sublimt Text (I'm on macOS and that's what did the trick; I had to Quit and start again, not just closing all open windows).

**Comment by OscSer** [comment]
> I had the same issue and weirdly what worked was to:
> 
> * remove pretty JSON
> * install it again
> * RESTART Sublimt Text (I'm on macOS and that's what did the trick; I had to Quit and start again, not just closing all open windows).

this worked for me, thanks.

**Comment by TheSecEng** [comment]
1. What command were you trying to run when this occured?

**Comment by t3link** [comment]
> 1. What command were you trying to run when this occured?

@TheSecEng This problem occurs after I reinstall the `sublime4` and `pretty json`. 
Using `Ctrl + Shift + P`
The `Format JSON` command has an error `sequence item 2: expected str instance, NoneType found`.
The `Minify JSON` command has an error `'NoneType' object has no attribute 'strip'`

However @zliuva 's solution works for me too. 

> I had the same issue and weirdly what worked was to:
> 
> * remove pretty JSON
> * install it again
> * RESTART Sublimt Text (I'm on macOS and that's what did the trick; I had to Quit and start again, not just closing all open windows).

**Comment by geek5nan** [comment]
I had the same issue, seems like today's release 1.0.5 has fixed it. If you still suffering this issue, try to do this below.

1. remove old `Pretty Json`
2. upgrade `Pretty Json` to `1.0.5`
1. restart Sublime Text

**Comment by TheSecEng** [comment]
Should be resolved with 1.1.0 release
