### ISSUE TITLE
The following incompatible package was found installed:

### ISSUE THREAD

**Issue by zhanggang807** [dzhibas/SublimePrettyJson#136]
Package Control

The following incompatible package was found installed:

Pretty JSON

This is usually due to syncing packages across different machines in a way that does not check package metadata for compatibility.

Please visit https://packagecontrol.io/docs/syncing for information about how to properly sync configuration and packages across machines.

To restore package functionality, please remove each listed package and reinstall it

**Comment by TheSecEng** [comment]
1. Are you syncing this package across machines?
2. Are those machines using the same Sublime Text version?

**Comment by tfarmerpgr** [comment]
I am going to go out on a limb and say it is from the ST4 upgrade. I had the same issue yesterday. Of all of the installed packages, Pretty JSON was the only one that had this message displayed after the upgrade. It displays this message on every start of Sublime Text 4, unless the package is removed.

- Package syncing not enabled
- Package installed via Package Control awhile back

**Comment by jaraco** [comment]
I encountered the same error alongside another plugin (Babel) after updating to ST4 4107. The error with Babel cleared after upgrading that plugin. I concur there's probably an incompatible change that occurred with the latest ST update that broken the plugin metadata.

**Comment by travelgirl-fics** [comment]
also have the same problem moving from ST 3 to 4.  no syncing (one machine only)

i remove pretty json, but i can't reinstall version 4.  the error:  expecting value line 1 column 1 char 0 whenever i try to prettify a json file

during installation, the description in package manager implies compatibility with sublime 2 and 3 only.  closing/reopening ST does not fix problem

windows 10 home, sublime 4 (build 4107)

**Comment by TheSecEng** [comment]
Can you share the JSON you are trying and a screen recording of it happening?

**Comment by travelgirl-fics** [comment]
this is the file that doesn't work -- it has comments for first and last line, but i believe that's allowed by spec:
[Ukulele Chordify Config - ORIGINAL Rob Caplan.json.txt](https://github.com/dzhibas/SublimePrettyJson/files/6548785/Ukulele.Chordify.Config.-.ORIGINAL.Rob.Caplan.json.txt)

this file doesn't sort (but doesn't display an error):
[settings.json.txt](https://github.com/dzhibas/SublimePrettyJson/files/6548794/settings.json.txt)

remove the .txt (github apparently doesn't approve of json files for upload

other files seem to work just fine.  random chance had be fail two of hundreds/thousands on my box :)

**Comment by TheSecEng** [comment]
@travelgirl-fics when you reinstall Pretty JSON fully quit sublime and launch again. Does the issue persist?

**Comment by TheSecEng** [comment]
Resolved with latest release

**Comment by travelgirl-fics** [comment]
uninstall pretty json
close ST
reopen ST
install pretty json
close ST
reopen ST
run PJ against the chordify/caplan file
fails

![Clipboard01](https://user-images.githubusercontent.com/84869877/119722918-b7b19980-be21-11eb-963f-c6beda453cef.jpg)

**Comment by TheSecEng** [comment]
> uninstall pretty json
> close ST
> reopen ST
> install pretty json
> close ST
> reopen ST
> run PJ against the chordify/caplan file
> fails
> 
> ![Clipboard01](https://user-images.githubusercontent.com/84869877/119722918-b7b19980-be21-11eb-963f-c6beda453cef.jpg)

This is due to that file having comments. This plugin follows JSON spec which doesn't support comments. 

https://github.com/dzhibas/SublimePrettyJson/issues/25

**Comment by travelgirl-fics** [comment]
huh.  would have sworn the spec allowed comments.  sigh.
thx :)
