### ISSUE TITLE
Chinese becomes unicode code when formatting

### ISSUE THREAD

**Issue by pihao** [dzhibas/SublimePrettyJson#137]
https://user-images.githubusercontent.com/3308394/119655449-2e6b8880-be5c-11eb-8478-203bb5aadce2.mov

Sublime Text version: 4107
PrettyJson version: v1.0.5

**Comment by feueraustreter** [comment]
With the following setting you can fix the error with German umlauts: ` "ensure_ascii": false `

Has the default setting been changed?

**Comment by TheSecEng** [comment]
It did get changed with ST4 but this is a error. I will revert back to it's default `false`

**Comment by TheSecEng** [comment]
Fixed
