### ISSUE TITLE
keep_arrays_single_line: true fails when array itself contains literal `"["`

### ISSUE THREAD

**Issue by keenahn** [dzhibas/SublimePrettyJson#138]
Example:

Good:
```
{"foo":["a","b","c"]}

// After formatting, becomes:

{
  "foo": ["a", "b", "c"]
}

```

Bad:
```
{"foo":["[","b","c"]}

// After formatting, becomes:

{
  "foo": [
    "[", "b", "c"]
}
```

 My guess is that there's something happening with your parser where it's looking for the `[` symbol

**Comment by TheSecEng** [comment]
Does this still happen? What version of sublime? What version of Pretty JSON? I can't reproduce this with the latest version of sublime or pretty json

**Comment by mlorenzo-stratio** [comment]
PrettyJSON 1.1.1 here. I have the same issue. With the following validated JSON:
```
{
  "calico": {
    "external_routers": [
      {
        "asNumber": "1234",
        "ip": "1.2.3.4",
        "name": "router"
      }
    ]
  }
}
```
If I `Format JSON` then it becomes:
```
{
  "calico":
  {
    "external_routers": [{, "asNumber": "1234", "ip": "1.2.3.4", "name": "router", }]
  }
}
```
which is clearly Invalid JSON

**Comment by TheSecEng** [comment]
> PrettyJSON 1.1.1 here. I have the same issue. With the following validated JSON:
> 
> ```
> {
>   "calico": {
>     "external_routers": [
>       {
>         "asNumber": "1234",
>         "ip": "1.2.3.4",
>         "name": "router"
>       }
>     ]
>   }
> }
> ```
> 
> If I `Format JSON` then it becomes:
> 
> ```
> {
>   "calico":
>   {
>     "external_routers": [{, "asNumber": "1234", "ip": "1.2.3.4", "name": "router", }]
>   }
> }
> ```
> 
> which is clearly Invalid JSON

I see, is the below the expected behavior? 

https://user-images.githubusercontent.com/32599364/121284357-94f79a00-c891-11eb-8e18-31f13566bcc2.mp4

**Comment by shelacek** [comment]
Hello,
I think the issue still occurs in version 1.2.1 :-(.

Source JSON:

```json
[{"a": {"b": "c"}}]
```

After `Format JSON` command:

```json
[{"a": {,"b": "c"},}]
```

My user settings only override `keep_arrays_single_line`:

```json
{
    "keep_arrays_single_line": true
}
```

**Comment by TheSecEng** [comment]
https://github.com/dzhibas/SublimePrettyJson/pull/156

**Comment by TheSecEng** [comment]
Next release fixes this
