### ISSUE TITLE
Package not available in Package control

### ISSUE THREAD

**Issue by azec-pdx** [dzhibas/SublimePrettyJson#14]
I have tried installing plugin via Package control, and repository is failing.
Here is error from Sublime 2 console:

Package Control: Error downloading package. HTTP error 500 downloading https://nodeload.github.com/dzhibas/SublimePrettyJson/zip/master

Could you please provide instructions for manual install in your readme?

THanks

**Comment by Tomirad** [comment]
After 7 years, this problem repeat itself.

I need this usefully plugin, but I can't install because the program  communicate with me printed text:

> Package Control: Error downloading package. HTTP error 500 downloading https://codeload.github.com/dzhibas/SublimePrettyJson/zip/master.
> error: Package Control
> 
> Unable to download Pretty JSON. Please view the console for more details.
