### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by gudata** [dzhibas/SublimePrettyJson#140]
When I try format a json I aways get the error: Expecting value: line 1 column 1 (char 0)
There is nothing in the console, and the JSON looks ok.
The jq is installed and working.
This error is after I upgraded to sublime 4017
![Selection_055](https://user-images.githubusercontent.com/25951/119819692-5230dc00-bef9-11eb-9b7b-366263685eef.png)

What I am doing wrong?

**Comment by TheSecEng** [comment]
You will likely need to force quit Sublime and restart again or re-install Pretty JSON, there are two versions and this have been a known issue when update to Sublime Text 4

**Comment by TheSecEng** [comment]
Any update on this?

**Comment by TheSecEng** [comment]
Closed due to inactivity
