### ISSUE TITLE
chinese characters be converted to unicode characters after format

### ISSUE THREAD

**Issue by wxynihao** [dzhibas/SublimePrettyJson#142]
in sublime4, chinese characters be converted to unicode characters after format.
for example,
```json
{"name": "张三"}
```
will be converted to 
```json
{
    "name": "\u5f20\u4e09"
}
```

**Comment by xiayuyuyu** [comment]
i found the bug too,  top!

**Comment by chechao** [comment]
https://github.com/dzhibas/SublimePrettyJson/issues/132#issue-862249894

**Comment by wxynihao** [comment]
> [#132 (comment)](https://github.com/dzhibas/SublimePrettyJson/issues/132#issue-862249894)

thanks

**Comment by fanfanfufu** [comment]
Preferences - Package Settings - Pretty Json - Settings
add "ensure_ascii": false,

**Comment by fanfanfufu** [comment]
Preferences - Package Settings - Pretty Json - Settings
add "ensure_ascii": false,

-- copy from #132 (comment)
