### ISSUE TITLE
pretty json 1.1.1 is not working in sumlime text 4107

### ISSUE THREAD

**Issue by huangchunhua13** [dzhibas/SublimePrettyJson#144]
OS：window10，sublime text 4107，but commands "ctrl + alt + j" is not reposnse，when I config key binding：
{
    "keys": [
        "ctrl+alt+j"
    ], 
    "command": "pretty_json"
},

it will Chinese garbled。

**Comment by romansavrulin** [comment]
+1

**Comment by cedverd** [comment]
for me too its not working OS: **Windows 10**, Sublime text Build: **4107**

**Comment by fengchuanfang** [comment]
for me too its not working OS: macOS 11.2.3,Sublime text Build: 4107

**Comment by fengchuanfang** [comment]
for me too its not working OS: macOS 11.2.3,Sublime text Build: 4107

**Comment by wxynihao** [comment]
Chinese garbled means unicode characters ? 
Preferences - Package Settings - Pretty Json - Settings
add "ensure_ascii": false,
have a try

**Comment by pixelecho** [comment]
same here OSX BigSur Sublime Text Build 4107

**Comment by mac521** [comment]
+1

**Comment by fffailed** [comment]
+1

**Comment by TheSecEng** [comment]
The key binding was removed due to many conflicts. Please see https://docs.sublimetext.io/guide/customization/key_bindings.html for how to set key bindings


@huangchunhua13 
> it will Chinese garbled。

Can you give some example text to show me? You probably need to set `"ensure_ascii": false`

**Comment by paulnieman** [comment]
Adding the following key bindings (Preferences > Key Bindings) worked for me:

```
{"keys": ["ctrl+alt+j"], "command": "pretty_json"},
{"keys": [ "ctrl+alt+m" ], "command": "un_pretty_json"},
```

Note: OS：window10，sublime text 4107

**Comment by tvkit** [comment]
> The key binding was removed due to many conflicts.

@TheSecEng  Conflicts?  The only reason I'm using Sublime is because of this plugin. Otherwise, I use Scite.

**Comment by huangchunhua13** [comment]
> The key binding was removed due to many conflicts. Please see https://docs.sublimetext.io/guide/customization/key_bindings.html for how to set key bindings
> 
> @huangchunhua13
> 
> > it will Chinese garbled。
> 
> Can you give some example text to show me? You probably need to set `"ensure_ascii": false`

This problem was solved,thank you!

**Comment by Bluefissure** [comment]
For me, the `{"keys": ["ctrl+alt+j"], "command": "pretty_json"}` works well but `{"keys": ["ctrl+alt+m"], "command": "un_pretty_json"}` is not functioning.

Using Command Palette Ctrl+Shift+P find “Pretty JSON: Minify JSON” is good.

Window 10 ST4 Build 4107

**Comment by pixelecho** [comment]
It also stops working via default Submenu item which was installed with pretty JSON Plugin by default. So the problem isn't only the shortcut!
