### ISSUE TITLE
All modifying commands convert russian letters to their unicode codes

### ISSUE THREAD

**Issue by Antieight** [dzhibas/SublimePrettyJson#145]
All modifying commands convert russian letters to their unicode codes.
For instance command  `Pretty JSON Format JSON` does this:
`
"name" : "Лиловый"   ->   "name": "\u041b\u0438\u043b\u043e\u0432\u044b\u0439"
`

**Comment by TheSecEng** [comment]
Set the following setting `"ensure_ascii": false`
