### ISSUE TITLE
ST4 { [ go to new line

### ISSUE THREAD

**Issue by alamothe** [dzhibas/SublimePrettyJson#147]
After formatting JSON, [ and { now go to the new line which is odd. Is there a setting for this? It used to be on the same line

**Comment by dotjim** [comment]
Hi there, I came here also thinking this was a bug. I found these defaults are now in the plugin settings file:

```json
    "brace_newline": true,
    "bracket_newline": true,
```

Setting these to `false` restores behaviour.

**Comment by alamothe** [comment]
Thanks! ❤️

**Comment by cristcost** [comment]
Me too ! Thanks! Please update the README.md file documenting this option
