### ISSUE TITLE
Pretty JSON for Sublime Text 4?

### ISSUE THREAD

**Issue by swaranga** [dzhibas/SublimePrettyJson#154]
I am trying to install Pretty JSON for my new Sublime Text 4 install in a new laptop. But when I search for "Pretty JSON" in package control, I see the description indicating it is only for Sublime 2 $ 3 (see screenshot below). I am currently using ST 4 Build 4113.

Is this just an issue with the text while the package works correctly with ST 4? I got confused because the github readm says "Prettify/Minify/Query/Goto/Validate/Lint JSON plugin for Sublime Text 3 & 4" and I did not want to install a wrong package and corrupt something.

![pretty-json](https://user-images.githubusercontent.com/7319946/126550302-485c4212-0964-40ab-b942-6b4e7024ffc9.png)

**Comment by TheSecEng** [comment]
It works properly on ST4. Readme just needs updated
