### ISSUE TITLE
pretty json on sublime text 4 generates an invalid json object when formatting a minified json string

### ISSUE THREAD

**Issue by ed-chang** [dzhibas/SublimePrettyJson#155]
minified json string to reproduce:
`{"abd":[{"abc":"abc","com":{"abc":"[{\"abc\":\"abc\",\"abc\":\"{\\\"abc\\\":{\\\"abc\\\":\\\"abcdef,xyz\\\"}}\",\"abc\":\"1\",\"abc\":\"abc\"}]","abcd":"efgh"}}]}`

sublime text build: 4113

**Comment by TheSecEng** [comment]
Thanks! Investigating

**Comment by TheSecEng** [comment]
This doesn't appear to be happening to me in the latest release. Can you confirm?

**Comment by ed-chang** [comment]
Just tried again. My sublime text was upgraded from version 3. I've tried uninstalling and installing pretty json again but got the same result.
![image](https://user-images.githubusercontent.com/82276475/130060243-18e8962d-f6de-4cfb-a950-005eccd0000e.png)

**Comment by ed-chang** [comment]
I tried this and problem solved.. Thanks!
`cd Pretty JSON`
`git checkout st3`

**Comment by githubhcj** [comment]
> I tried this and problem solved.. Thanks!
> `cd Pretty JSON`
> `git checkout st3`

你的这个cd 命令仅是在 sublime3 下可以解决吧，4 中没有 Pretty JSON这个文件夹

**Comment by vsethi13** [comment]
I am facing the same issue. ST Build# 4121
I don't want to bum down the version of pretty json package as @ed-chang did because I am afraid it might break something else.
