### ISSUE TITLE
JSON Minifier produces invalid JSON when character count exceeds 29,921

### ISSUE THREAD

**Issue by fastackl** [dzhibas/SublimePrettyJson#157]
To replicate:
Open [210811_claire.txt](https://github.com/dzhibas/SublimePrettyJson/files/6965898/210811_claire.txt) in Sublime
Run `Pretty JSON: minify JSON`
You'll see the JSON won't validate syntax
![image](https://user-images.githubusercontent.com/80379118/128970437-708f0322-f42f-4df2-9547-ca16911a5d3a.png)

Then delete any 406 characters in the file to bring the character count down to 29,921
Run `Pretty JSON: minify JSON`
You'll see the JSON will validate now
![image](https://user-images.githubusercontent.com/80379118/128970761-52c8119b-b50a-45a2-9f4e-66b152873fab.png)

**Comment by TheSecEng** [comment]
It looks like it is valid, but syntax highlighting is disabled. After you minify it can you run "Pretty JSON: Validate" and check the status bar?

My testing shows that this is working as expected

**Comment by fastackl** [comment]
Yeah actually it says it's valid 
![image](https://user-images.githubusercontent.com/80379118/129309845-49e5ff94-e038-4f27-976e-a4457dff3cbb.png)

So weird because if you delete a 406 character chunk out, the syntax highlighting reenables.

Before 
![image](https://user-images.githubusercontent.com/80379118/129309958-ccf3338e-8404-48ed-a020-a015f7031dd0.png)

After 
![image](https://user-images.githubusercontent.com/80379118/129309990-6f4fba1b-4260-4243-854a-67651f6146c0.png)

So maybe the problem is with the syntax highlighter and not JSON Pretty.

Reason it's more than just annoying is that whatever is causing it is breaking the hash between a JSON minified on Sublime vs a JSON minified outside of Sublime (say with https://codebeautify.org/jsonminifier or any other online JSON beautifier, they all produce the same hash)

But, it might not be an issue with JSON Pretty could be the syntax validator throwing in some invisible character or something 🤔

**Comment by TheSecEng** [comment]
Are you using Sublime Text 4. I think this is intentional with either long lines or file size. 

If using ST4. Maybe play with the `syntax_detection_size_limit` setting.

**Comment by fastackl** [comment]
Cool ok will try that thanks. I'll close this for now as I don't think it's Pretty JSON related 🙏
