### ISSUE TITLE
keybinding for jq_pretty_json opens but with no search/filter field

### ISSUE THREAD

**Issue by lwalton-turnto** [dzhibas/SublimePrettyJson#158]
Using ST4 on Mac OS Big Sur  .... I added the following keybinding. 

```[
	{ "keys": ["super+j"], "command": "jq_pretty_json" }
]
```
It opens the new two paned window but has not search/filter/query field like it has if I open it from Command Palette search & enter.

Also, I often accidentally hit ENTER in the search/filter/query field and then I don't know how to get it back.  

Is there a way to do that without closing it and restarting from the Command Palette again? 

Thanks!

**Comment by iamabook** [comment]
To show ./jq view with ./jq query field, you need to run command "jq_query_pretty_json", not "jq_pretty_json".

See file "Default.sublime-commands"

**Comment by lwalton-turnto** [comment]
Hmm.  I'm not sure how/why when I pasted my example above I got jq_pretty_json because jq_query_pretty_json is what I have in my keybindings. and it isn't working for me. 

[
	{ "keys": ["super+j"], "command": "jq_query_pretty_json" }
]

sorry for the time waste but I do still have this problem. Can you reopen?
