### ISSUE TITLE
Incorrect syntax logic

### ISSUE THREAD

**Issue by AslanMussinov** [dzhibas/SublimePrettyJson#167]
It always enforces default JSON syntax when calling "pretty_json" command even with overridden settings

**Comment by TheSecEng** [comment]
Thanks! I’ll have to look into checking the current syntax before re-assignment.

**Comment by TheSecEng** [comment]
Fix in next release with a `set_syntax_on_format` setting

**Comment by TheSecEng** [comment]
Now controlled by a setting
