### ISSUE TITLE
[Bug] "Format JSON Lines" on a "plain pretty JSON" file, triggers "[Error]: " times N (where N is the number of lines in the file) 

### ISSUE THREAD

**Issue by stdedos** [dzhibas/SublimePrettyJson#169]

**Comment by TheSecEng** [comment]
Example JSON would help a bunch

**Comment by TheSecEng** [comment]
Fixed in next release

**Comment by stdedos** [comment]
What was the underlying issue? 

I don't see new commits on master 😕

**Comment by TheSecEng** [comment]
I wasn't tracking errors. So even after errors occurred it kept rd trying to format. Now I track errors. I'll push changes shortly.
