### ISSUE TITLE
Install description shows supported Sublime Text versions as 2 & 3

### ISSUE THREAD

**Issue by TeddMcAdams** [dzhibas/SublimePrettyJson#170]
![image](https://user-images.githubusercontent.com/15876990/171900541-e8346d8a-db26-4bc9-a5cf-f2124037bac3.png)

versus `Prettify/Minify/Query/Goto/Validate/Lint JSON plugin for Sublime Text 3 & 4` on the README.md file.

**Comment by TheSecEng** [comment]
@dzhibas Can you update the repo **Description** to `Prettify/Minify/Query/Goto/Validate/Lint JSON plugin for Sublime Text 3 & 4`

**Comment by dzhibas** [comment]
thank you guys, this is done
