### ISSUE TITLE
Duplicate key is removed by format json command

### ISSUE THREAD

**Issue by SpL1Ne** [dzhibas/SublimePrettyJson#171]
```
{
	"key1":"value","key2":"value2","key3":"value3","key1":"value4"
}
```
Formatted to
```
{
    "key1": "value4",
    "key2": "value2",
    "key3": "value3"

}
```

Expected result:
Format without removing duplicate key or show an error and don't format at all.

Sublime 4, build 4126, default settings for Pretty JSON, last version installed via Package Control.

**Comment by TheSecEng** [comment]
Fixed in next release
