### ISSUE TITLE
Message for invalid JSON remains even after fixing and revalidating JSON

### ISSUE THREAD

**Issue by khorn** [dzhibas/SublimePrettyJson#173]
Consider the following (invalid, it's missing a comma) JSON:

```json
{
    "key1": "value1"
    "key2": "value2"
}
```

If I use PrettyJson to validate this JSON (using the "Pretty JSON: Validate" command) it will of course fail, and give a message in the status bar explaining why, like so:

![image](https://user-images.githubusercontent.com/815352/183116309-4b3cdf75-e0b8-4c9d-ae13-ad026e1dea2e.png)

If I then fix the offending JSON, making it valid, and then rerun the "Pretty JSON: Validate", PrettyJson correctly judges it valid, but the message about it being invalid in the status bar remains.  Example:

![image](https://user-images.githubusercontent.com/815352/183116747-85397483-941f-4213-b11c-38deee068f87.png)

This message persists until one of the following happens:
- SublimeText is restarted
- the "Pretty JSON: Validate" command is run again, and finds that the JSON being evaluated is invalid in some different way, in which case it will be overwritten with the new invalid message

When reporting JSON as valid, PrettyJson should remove the old message about invalid JSON.

**Comment by TheSecEng** [comment]
Will fix in next release
