### ISSUE TITLE
Add option to automatically pretty json on save

### ISSUE THREAD

**Issue by nodesocket** [dzhibas/SublimePrettyJson#40]
Is this possible?

**Comment by vishalshah-org** [comment]
+1!

**Comment by Cellule** [comment]
I managed to do this with
https://github.com/twolfson/sublime-hooks/blob/master/hooks.py
and a language specific settings
```js
{
  "on_pre_save_language": [
    {
      "command": "pretty_json"
    }
  ]
}
```

**Comment by andreis** [comment]
I too would like this. @dzhibas you can see this (or many similar projects) for an idea of how to do it: https://github.com/wistful/SublimeAutoPEP8

**Comment by dzhibas** [comment]
```
    "pretty_on_save": false
```

flip it to **true**

**Comment by vsiv** [comment]
👍
