### ISSUE TITLE
Does not work in build 3065

### ISSUE THREAD

**Issue by psytechno604** [dzhibas/SublimePrettyJson#48]

**Comment by promorphus** [comment]
I'm having the same issue, however, there may be more of a build breakage then a code breakage. Installing through package manager ultimately fails. However, git-cloning the repo into the packages folder gives a working build.

**Comment by maksad** [comment]
@promorphus @psytechno604 

Please check issue:
https://github.com/dzhibas/SublimePrettyJson/issues/49

**Comment by TheSecEng** [comment]
Closing issue as no additional updates no context for issues.
