### ISSUE TITLE
Does not work in build 2221

### ISSUE THREAD

**Issue by pepkin88** [dzhibas/SublimePrettyJson#49]
I don't know what is the cause, but I cannot properly install this package from Package Control. After install there is nothing that changed in the editor: no custom settings menu item, <kbd>Ctrl+Alt+J</kbd> doesn't work, no new items in the Command Palette.
Files appear to be properly placed in the `Packages` folder. Also no errors in console.
My version of Sublime Text is 2.0.2, build 2221, used on Windows 8.

**Comment by promorphus** [comment]
I responded in the other ticket for this as well, but having tested on both platforms, I'll respond here as well. The install via package manager fails, but manually installing via git clone succeeds.

**Comment by pepkin88** [comment]
@promorphus Thanks. I experimented a bit and found, that all you need to do to make it work, is removing space from the folder name `Pretty JSON` (make it `PrettyJSON`).

**Comment by maksad** [comment]
I had the same issue and @pepkin88 trick worked for me. 👍

**Comment by TheSecEng** [comment]
As this is a ST2 issue, we will not be renaming the package. ST is no longer updated or maintained. We will be dropping ST2 support.
