### ISSUE TITLE
Sort object alphabetically by keys

### ISSUE THREAD

**Issue by RichardLitt** [dzhibas/SublimePrettyJson#53]
A lot of times, I want to have an object sorted alphabetically by keys just to help me read it better. Specifically, this applies to package.json and manifest.json files. I wonder if it would be too hard to implement an option that does that as part of this package?

**Comment by lime** [comment]
This is already available as the `sort_keys` setting, i.e. if you edit your `PrettyJSON.sublime-settings` to include 
```json
{
    "sort_keys" : true
}
```
you get this behaviour. :)

It's a plugin-level setting, so in case you don't want the same behaviour every time you'll have to edit it back and forth between uses. Making it available as an additional command could be nice, although I guess most users are fine with having it turned on/off globally.

**Comment by dzhibas** [comment]
thank you @lime 

i also recently added new menu item "**Pretty JSON: Format and Sort JSON**" which bypass checking of config sort_keys and force sorting just for that command

**Comment by anand853** [comment]
do i need to restart after setting sort_key to true? i do not see any change in the order of the sort_key value update

**Comment by wzup** [comment]
@lime 
That built-in feature of ST doesn't work for nested objects! Only for flat single level objects.
Since almost always objects are nested the feature almost always break your code.

**Comment by ThaJay** [comment]
very nice for the diff of imported json files. Before I used this option the diff would be pretty much the entire file.
