### ISSUE TITLE
./jq doesnt work on windows

### ISSUE THREAD

**Issue by solo12zw74** [dzhibas/SublimePrettyJson#54]
Try to use ./jq module of ur plugin and it said that "jq tool is not available on your system". But i now that it is. But what more interesting - it works early in 2014. Try to analyse your sources and find that this code

```python
s = subprocess.Popen(["jq", "--version"],
                         stderr=subprocess.PIPE,
                         stdout=subprocess.PIPE)
```

calls an error "WinError6"
And find this [python issue report](http://bugs.python.org/issue3905)

And it solves a problem in my case:

```python
s = subprocess.Popen(["jq", "--version"],
                         stdin=subprocess.PIPE,
                         stderr=subprocess.PIPE,
                         stdout=subprocess.PIPE)
```

**Comment by DrStrangepork** [comment]
I am new to Sublime, and I want to set this up as well. It is not working for me either, with the same error.

Where can I find the fix you mentioned? I am using Sublime Build 3065.

**Comment by solo12zw74** [comment]
@DrStrangepork,  to apply my fix you need to [install SublimePrettyJson plugin from sources](https://github.com/dzhibas/SublimePrettyJson#or-manually-install) and edit `PrettyJson.py` file in line 32. Paste my snippet instead.

**Comment by DrStrangepork** [comment]
Works, thanks!

**Comment by dzhibas** [comment]
added stdin into plugin
