### ISSUE TITLE
Please allow support for mongoDB find results

### ISSUE THREAD

**Issue by rockarena** [dzhibas/SublimePrettyJson#55]
Please allow support for mongoDB types in values and no mandatory comma between objects

**Comment by dzhibas** [comment]
can you please paste here an example of such json ?

**Comment by rockarena** [comment]
{ _id: Object("ababaaa0a10"), type: "food", item: "aaa", ratings: [ 5, 8, 9 ] }
{ _id: 6, type: "food", item: Number(99), ratings: [ 5, 9 ] }
{ _id: 7, type: "food", item: "ccc", ratings: [ 9, 5, 8 ] }
