### ISSUE TITLE
Option for keeping long arrays on a single line when prettifying

### ISSUE THREAD

**Issue by sandromartis** [dzhibas/SublimePrettyJson#57]
Hey there

Would it be possible to have an option to keep long arrays on a single line when prettifying a JSON?

I work a lot with large JSON files that contain 3D geometries like vertices, faces, etc. that are stored in large arrays. When prettifying those it puts all the array elements on an individual line.
It would be great to have an option to just keep arrays as they are and prettify everything else.

Unfortunately I don't know much about Sublime Packages and how PrettyJson works under the hoods, but if it's possible I can look into it and make a pull request.

Cheers,
Sandro

**Comment by goodforenergy** [comment]
I'd love this too :+1:

**Comment by dzhibas** [comment]
done. check https://github.com/dzhibas/SublimePrettyJson/blob/master/README.md#default-configuration options for "arrays" you need to tweek these 2:

```
    "keep_arrays_single_line": true,
    "max_arrays_line_length": 120
```
