### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by Gtskk** [dzhibas/SublimePrettyJson#58]
When I use the `jq` function in Windows 10, I get the following error:

![image](https://cloud.githubusercontent.com/assets/2942038/9979197/e26d2ef4-5f91-11e5-8d30-6515bc61f486.png)

When I change the code in line 200 
```python
out, err = p.communicate(bytes(raw_json))
```
to
```python
out, err = p.communicate(raw_json.encode('utf-8'))
```
, it works.

Hope it helps. Or maybe another better solution.

**Comment by acntwww** [comment]
change line 200 to 
`out, err = p.communicate(unicode(raw_json).encode('utf-8'))`
I fork and in [my repo](https://github.com/acntwww/SublimePrettyJson)
