### ISSUE TITLE
Pretty print should set syntax json

### ISSUE THREAD

**Issue by vkaushal21** [dzhibas/SublimePrettyJson#64]
When doing pretty print json it should automatically set syntax json. It can be a user option if everybody doesn't want it enabled by default.

**Comment by dzhibas** [comment]
it does that already, tho it's switching on only if you:

1. prettifying all file (not small selection)
2. you are in "Plain text" doing that

https://github.com/dzhibas/SublimePrettyJson/blob/master/PrettyJson.py#L98
