### ISSUE TITLE
Space between key and value after colon {:}   

### ISSUE THREAD

**Issue by sweetw0r** [dzhibas/SublimePrettyJson#66]
Can you add one more setting to remove extra space between key and value after colon? Like it works on https://jsonformatter.curiousconcept.com

**Expected:**
"messageType":"payments",

**Actual:**
"messageType": "payments",

**Comment by dzhibas** [comment]
now default setting files looks like this:

`{
    "use_entire_file_if_no_selection" : true,
    "indent" : 4,
    "sort_keys" : true,
    "ensure_ascii" : false,
    "line_separator": ",",
    "value_separator": ": "
}`

just change or add *value_separator* and remove extra space and you good

**Comment by sweetw0r** [comment]
Good approach, Sir!
