### ISSUE TITLE
Sort by selected feature would be very useful

### ISSUE THREAD

**Issue by sweetw0r** [dzhibas/SublimePrettyJson#68]
Sort json by key names like this service does - http://jsoneditoronline.org
Documentations of the service - http://jsoneditoronline.org/doc/index.html
<img width="233" alt="screen shot 2016-06-22 at 11 29 37 am" src="https://cloud.githubusercontent.com/assets/12688470/16278700/bfe347f6-386c-11e6-9b7c-7e1af75b8be6.png">

Expected:
- User can sort keys of selected object by alphabet

**Comment by sweetw0r** [comment]
The functionality is already implemented :)

**Comment by sweetw0r** [comment]
But would be great to separate those configurations:
```
"use_entire_file_if_no_selection" : true, 
"sort_keys" : true
```

by having: 
```
"use_entire_file_if_no_selection" : true, 
"sort_keys" : false,
"sort_keys_if selection" : true
```

**Comment by dzhibas** [comment]
i would say it would make more sense to make a separate menu item just to sort keys

**Comment by dzhibas** [comment]
added separate menu item just sort once you need and you can keep default setting on false

**Comment by sweetw0r** [comment]
Sorry. I didn't follow how it works now.?

**Comment by sweetw0r** [comment]
I think I got it now!
User needs to:
1) Select the object from "{" to "}" 
2) Then sort it by menu ⇧+⌥+P (Shift + Option + P) > Pretty JSON: Format and Sort JSON
3) Then unselect everything
4) And apply ⌃+⌥+J (Control + Option + J) to put missing indentations back

User default settings: 
```
{
    "ensure_ascii":true,
    "indent":4,
    "line_separator":",",
    "use_entire_file_if_no_selection":true,
    "sort_keys":false,
    "value_separator":":"
} 
```
P.S. It needs a bit practice in order to do it quickly;) Thanks!
