### ISSUE TITLE
Pretty JOSN after copy/paste from xls sheet cell. Quad quotes fix for ""companyId"":""COMPANYID"",

### ISSUE THREAD

**Issue by sweetw0r** [dzhibas/SublimePrettyJson#69]
Test case:
1) Copy a cell with JSON from an Excel sheet
2) Paste it into the Sublime
<img width="255" alt="screen shot 2016-07-14 at 11 25 53 am" src="https://cloud.githubusercontent.com/assets/12688470/16850885/d71009fa-49b5-11e6-9396-0490397da8d5.png">

**Comment by TheSecEng** [comment]
Not planned, the simplest solution would be to strip double quotes with Sublimes Find and Replace function.

https://docs.sublimetext.io/search_and_replace/search_and_replace_overview.html?highlight=find%20replace
