### ISSUE TITLE
Comments in JSON files

### ISSUE THREAD

**Issue by Kristinita** [dzhibas/SublimePrettyJson#70]
Hello, my`json` files have comments, I don't want to delete them. But your plugin doesn't format files with comments.

For example, beginning of my file:

```
[
    // Scroll bar
    {
        "class": "scroll_bar_control",
        "layer0.tint": [0, 250, 154],
        "layer0.opacity": 1,
    },
```

When I try to format a code, in Status Bar appears:

> Expecting object: line 2 column 5 (char 6),

![Expecting object](http://i.imgur.com/NlbBvOH.png)

If I type in this file in the command palette `Pretty JSON: Validate`, a dialog box appears with the inscription:

> Invalid JSON

![Invalid JSON](http://i.imgur.com/jZDRivk.png)

In files that do not contain comments `JSON is valid`. How can I format my file contains comments?

Thanks.

**Comment by alexfowler** [comment]
I have the same problem as well, would be nice if comments were supported

**Comment by sweetw0r** [comment]
+1

**Comment by Kristinita** [comment]
@alexfowler, @sweetw0r, prettify json with comments is nice, but I think, it's no to be realized in this plugin, because Pretty JSON only for valid json. json with comments [now is non-valid](https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr).

Fortunately, we can prettify json with comments in any JavaScript beautifier. I recommend to use [CodeFormatter](https://github.com/akalongman/sublimetext-codeformatter) plugin.

If you all understand Russian language, you may read my [question](http://ru.stackoverflow.com/q/566060/199934) and [answer](http://ru.stackoverflow.com/a/566061/199934) about this problem.

Thanks.

**Comment by sweetw0r** [comment]
// - is how sublime comments json. So it makes sense to have the feature in this cool plugin that can omit // lines. We all have to comment some json structure at some point and that is how it's gonna be for quite some time. The plugin was created to make our lives easier, so why stop now? Can we give it another shot please?

**Comment by Kristinita** [comment]
@sweetw0r , see my previous comment.

Thanks.

**Comment by sweetw0r** [comment]
@Kristinita, I saw it and disagree!
