### ISSUE TITLE
Setting for validate "on_post_save"

### ISSUE THREAD

**Issue by FeBe95** [dzhibas/SublimePrettyJson#71]
For Sublime's own files (e.g. .sublime-settings) comments are allowed like this:
```
{
    "setting1": true,
    // "setting2": true,
    "setting3": true
}
```
As there is no setting to stop the plugin from validating on save, it always gives a JSON error.
Adding
```
16:    auto_val = s.get("validate_on_save", False) // or True
17:    if auto_val and "JSON" in view.settings().get('syntax'):
``` 
to PrettyJsonListeners.py should be an easy-to-implement solution to turn off post save validation, if a user is willing to do so

**Comment by dzhibas** [comment]
sorry mate, will bring out setting to turn it off. thanks for raising

**Comment by dzhibas** [comment]
put `"validate_on_save": false` into your user settings. thank you again for reporting this

**Comment by FeBe95** [comment]
Thanks for the quick response and implementation!
