### ISSUE TITLE
Allow multiple jsons/json lines

### ISSUE THREAD

**Issue by drevicko** [dzhibas/SublimePrettyJson#72]
It'd be handy to be able to e.g. prettify a file containing multiple json strings, such as what you get from the Twitter streaming API or a [json lines](http://jsonlines.org/) formatted file.

**Comment by TheSecEng** [comment]
This now exists in the ST3 release.

**Comment by TheSecEng** [comment]
![2020-05-19_15-49-52 (1)](https://user-images.githubusercontent.com/32599364/82371612-7b668480-99e8-11ea-9aa6-0d3e2c051951.gif)

**Comment by drevicko** [comment]
NIce! Many thanks!

**Comment by TheSecEng** [comment]
Going to leave this open till ST4 version has it

**Comment by hsleewis** [comment]
Any chance this is on the roadmap for the ST4 version as well?

**Comment by TheSecEng** [comment]
> Any chance this is on the roadmap for the ST4 version as well?

Will be pushing a PR that contains this feature today
