### ISSUE TITLE
keep_arrays_single_line ...

### ISSUE THREAD

**Issue by cheenu2** [dzhibas/SublimePrettyJson#74]
Try formatting this with
keep_arrays_single_line: true

The second array is NOT formatted to single line
{
  "good": [50, 200, 300, 450, 550, 800, 1100, 1100, 1200, 1100, 1150, 1200, 1100, 1250, 1250, 1150, 1100, 950, 900, 1000, 1050],
  "bad": [50, 200, 300, 450, 550, 800, 1100, 1100, 1200, 1100, 1150, 1200, 1100, 1250, 1250, 1150, 1100, 950, 900, 1000, 1050, 1200, 1100, 1000, 1000, 700, 700, 600]
}

**Comment by dzhibas** [comment]
please check readme there is another option

`max_arrays_line_length - 120 if array for example '["a", "b", 123213, ....]' length will reach max it will be kept multi-line (for beauty)`

looks like its because of max arrays line length second one was not
