### ISSUE TITLE
windows下怎么安装

### ISSUE THREAD

**Issue by l270378034** [dzhibas/SublimePrettyJson#78]

**Comment by qimuxi1990** [comment]
这是sublime text软件的一个插件，安装方法与操作系统无关。
如果sublime text已有package control (如没有请按照[此链接](https://packagecontrol.io/installation)安装package control)
打开sublime text，按ctrl+shift+p，输入install package并选择，输入pretty json检索插件，选择并等待安装完毕。退出sublime text并重新打开即可使用。
使用方法见[readme](https://github.com/dzhibas/SublimePrettyJson/blob/master/README.md).
reference: [readme.md](https://github.com/dzhibas/SublimePrettyJson/blob/master/README.md)

**Comment by TheSecEng** [comment]
Not sure what this issue relates to. Any updates ?

Issue with be closed in 5 days if no valid update is given.

**Comment by TheSecEng** [comment]
Due to no response, closing.
