### ISSUE TITLE
PrettyJson does not prettify JSON with multiple lines

### ISSUE THREAD

**Issue by vietzerg** [dzhibas/SublimePrettyJson#82]
When I tried to prettify a JSON file with multiple lines, Sublime Text said `Extra data: line 2 ... - line 20123`.

A preview of my JSON file:
![image](https://cloud.githubusercontent.com/assets/26194721/26049594/bb9d055e-3985-11e7-8312-0c1d942be297.png)

Please address this! Thank you!

**Comment by davidAlfonsoHermelo** [comment]
I have the exact same problem. It would be nice if it was resolved.

**Comment by TheSecEng** [comment]
@davidAlfonsoHermelo @vietzerg do you have a sample set of json to test this?

**Comment by TheSecEng** [comment]
Duplicate of #72 

Will implement soon
