### ISSUE TITLE
Love it - would be great if you could add array collapsing too

### ISSUE THREAD

**Issue by egeakpinar** [dzhibas/SublimePrettyJson#83]
Works great - thanks a lot!

Would be great if you could add the ability to collapse/expand arrays too (currently I can collapse/expand any dictionary, but not arrays)

**Comment by egeakpinar** [comment]
Well good news I guess, it now started working for arrays too (maybe a restart was needed, not sure) Thanks!

**Comment by egeakpinar** [comment]
Hmm seems it occurs when the file is very long (180k lines for me)

**Comment by TheSecEng** [comment]
ST is in charge of the fold and unfolding of arrays / dictionaries. 

Going to close this issue for now as I can't replicate with 400K lines of json
