### ISSUE TITLE
Some Default and User Settings do not work

### ISSUE THREAD

**Issue by linmdotor** [dzhibas/SublimePrettyJson#86]
Changing the settings file does not do any difference.

i.e.: Setting `"pretty_on_save": true,` is not working.
The same with other settings as `validate_on_save`

Changing key indent `"indent" : "\t",` works fine actually.

**Comment by dzhibas** [comment]
@linmdotor `pretty_on_save` and `validate_on_save` works only on JSON syntax files. can you check again if you have file with Json syntax specified and then try save (check if it's validated and prettified)

**Comment by linmdotor** [comment]
I checked the Syntax, and was JSON.

Doing the validate and prettified manually works well, the problem is with the saving event.

I´ve applied the changes of the PR #79, and now it works fine with autosave.

Probably the problem it's related with the blanks in the path of the settings file...

**Comment by linmdotor** [comment]
But thinking on it... the "indent" value worked fine before the changes. :S

**Comment by TheSecEng** [comment]
See #49
