### ISSUE TITLE
Keybinding conflicts with GitGutter

### ISSUE THREAD

**Issue by deathaxe** [dzhibas/SublimePrettyJson#87]
https://github.com/dzhibas/SublimePrettyJson/blob/77a8fbab60164161085a154025cae3f1c0889425/Default%20(Windows).sublime-keymap#L15

Please change.

**Comment by TheSecEng** [comment]
@deathaxe have any recommendations for alternate

**Comment by deathaxe** [comment]
Haven't made up my mind about another key binding. I wouldn't expect a code formatter to need to be bound to keys in general. I'd found it most natural to run it automatically when saving the file (via `on_pre_save` event) or manually from the command palette by default.

**Comment by TheSecEng** [comment]
Makes sense, that key binding is for activating the `jq` filtering, but still not sure its heavily used. I'll remove it from the ST3/4 branches on next release. And leave it up to the end user if they want it. Highly doubt its used.

**Comment by TheSecEng** [comment]
This will be resolved in the ST4 channel on next release
