### ISSUE TITLE
Unicode escape sequences are converted to unicode characters

### ISSUE THREAD

**Issue by RockyMM** [dzhibas/SublimePrettyJson#90]
Hey there, 

Using PrettyJSON on Win 10, latest Sublime.

For text that contains Unicode escape sequences, such as "\ufffd", these are actually translated to Unicode character, which is unexpected.

For instance:

```{"key":"Fremdz\ufffdhler","value":"false"}```

is converted to:

```
{
  "key": "Fremdz�hler",
  "value": "false"
}
```

**Comment by TheSecEng** [comment]
@RockyMM this is solved with the `ensure_ascii`


![2020-04-16_17-10-47 (1)](https://user-images.githubusercontent.com/32599364/79507182-4344de00-8005-11ea-9d03-4a65436b7295.gif)

**Comment by RockyMM** [comment]
Nice! Thanks!
