### ISSUE TITLE
Add notification when parsing JSON with multiple identical keys

### ISSUE THREAD

**Issue by pizza2code** [dzhibas/SublimePrettyJson#91]
Recently, I used this plugin to debug JSON files which had multiple identical keys (each containing large arrays).  At first, I totally thought something was buggy with this plugin because I didn't realize the files contained multiple identical keys, and I kept seeing large portions of JSON disappear in the prettify step.  It would be nice to see an emphatic warning somewhere when we prettify a poorly-formed JSON file like that.

Thanks for the plugin, by the way, I use it every day!

**Comment by TheSecEng** [comment]
#111 will provide an error similar to the following when validating

<img width="217" alt="image" src="https://user-images.githubusercontent.com/32599364/79506055-5c4c8f80-8003-11ea-8857-33b13da2502d.png">

**Comment by TheSecEng** [comment]
Resolved in Latest release st3-1.0.1
