### ISSUE TITLE
jq integration doesn't work on Windows

### ISSUE THREAD

**Issue by kohenkatz** [dzhibas/SublimePrettyJson#94]
Sublime Text v3.0 build 3143

I have the `jq` binary for Windows in `C:\Programs\jq.exe`, and `C:\Programs` is in my `PATH`.
When I open a Command Prompt window and run `jq --version`, I get `jq-1.6rc1-10-g7fd9e86`, so the `PATH` is definitely set and working correctly.

However, when I press Ctrl+Shift+Alt+J, the status bar says "./jq tool is not available on your system. http://stedolan.github.io/jq".

How can I get this package to recognize that `jq` is already installed?

**Comment by wjakobw** [comment]
Note that you have to restart ST if you add the file to path after trying to find it once. The package remembers that it has tried looking and not found it.

Works for me on W10 and Sublime Text 3.1.1 Build 3176.

**Comment by TheSecEng** [comment]
This can also be resolved with the new setting `jq_binary`

**Comment by ShahidRKhan** [comment]
had the same issue with sublimetext 3.
but worked
only after I added its parent folder to the environment variable "Path"
And renamed the downloaded file to "jq.exe"
