### ISSUE TITLE
Showing strings with \n better

### ISSUE THREAD

**Issue by AbdealiJK** [dzhibas/SublimePrettyJson#95]
It would be pretty awesome if this could show me JSON lines with `\n` with a proper line break.

Frequently due to the no-multiline support of json, I have json like:

```
{
...
    "code_string": "def func_name(d1):\n\timport numpy as np\n\tdef inner_function():\n\t\tif d1 < 2:\n\t\t\treturn 0\n\t\telse:\n\t\t\treturn 1\n\treturn_val = inner_function()\n\treturn float(return_val)",
...
}
```

would be pretty cool if this can be seen properly somehow :)  (with rendered line breaks and tabs)

**Comment by TheSecEng** [comment]
How do you imagine this working ? Just render it with the new lines and tabs ? Might be possible. I’ll look into it as a phantom potentially

**Comment by TheSecEng** [comment]
As this is far out of JSON spec, this will not be supported
