### ISSUE TITLE
Only jq_pretty_json visible in command palette

### ISSUE THREAD

**Issue by atticusfyj** [dzhibas/SublimePrettyJson#98]
OS: mac OS 10.13.5
Sublime: 3.1.1 (build 3176)

Only "Pretty JSON: JSON query with ./jq" is visible in command palette. Commands such as "Pretty JSON: Format (Pretty Print) JSON" are not accessible either through command palette or through keyboard shortcut.

![image](https://user-images.githubusercontent.com/33437563/42364261-296c4104-812d-11e8-9161-42c8cf27793a.png)

**Comment by Demetrio92** [comment]
Reinstalling should help. I had this problem as well.  Pretty JSON with `./jq` in it never worked again, but "sort and format" does the trick.

**Comment by redfarg** [comment]
Same exact issue for me. I'm also on Mac (10.13.4), with the same Sublime version/build.

Tried installing the package multiple times and also cloning the repo directly to the packages folder.

**Comment by TheSecEng** [comment]
@atticusfyj is this still an issue?

**Comment by TheSecEng** [comment]
Due to no response, closing issue.
