### ISSUE TITLE
Using inside a python script

### ISSUE THREAD

**Issue by Demetrio92** [dzhibas/SublimePrettyJson#99]
Without looking though the code, I will just ask this stupid question. Can I use this amazing tool within a python script? 
I export something to json, and I open sublime and look at it. I can easily sort and format it thanks to this nice package, but I was wondering whether there is a way to do this on a file from a python script. (I know there is, I am just not sure where to look for)
Thanks!

**Comment by TheSecEng** [comment]
The logic for formatting and sorting has no reliance on ST API. Currently, breaking this out into a library is not current something we are looking to to do. I’ll be leavening this open for now, in case that changes.
